In [7]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import solve
from scipy.sparse.linalg import spsolve

In [8]:
Nb=5
print(np.eye(Nb,k=-1)-2*np.eye(Nb)+np.eye(Nb,k=1))

[[-2.  1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  1. -2.]]


# Comparaison matrice creuse/pleine en memoire et temps 

In [9]:
import time
import scipy.sparse as sparse
Nb = 10**4
print("++++++++ Matrice pleine ++++++++")
Adense = np.eye(Nb,k=-1)-2*np.eye(Nb)+np.eye(Nb,k=1)
print("Dimensions de Adense :",Adense.shape,"; taille mémoire :",
      Adense.nbytes,"octets")
print("++++++++ Matrice creuse ++++++++")
Acreuse = sparse.eye(Nb,k=-1)-2*sparse.eye(Nb)+sparse.eye(Nb,k=1)
print("Une matrice creuse est stockée sous forme de 3 vecteurs")
print("\tAcreuse.indices de dimension",Acreuse.indices.shape)
print("\tAcreuse.indptr de dimension",Acreuse.indptr.shape)
print("\tAcreuse.data de dimension",Acreuse.data.shape)
taille = Acreuse.indices.nbytes + Acreuse.indptr.nbytes + Acreuse.data.nbytes
print("Dimensions de Acreuse :",Acreuse.shape,"; taille mémoire :",
      taille,"octets")
print("Ratio memoire:",Adense.nbytes/taille)
bdense = np.ones(Nb)



start_time = time.time()
x1 = solve(Adense,bdense)
time_dense = time.time() - start_time
print("--- %s seconds ---" % (time_dense))
start_time = time.time()
x2 = spsolve(Acreuse,bdense)
time_creux = time.time() - start_time
print("--- %s seconds ---" % (time_creux))
print("Ratio temps ",time_dense/time_creux)


++++++++ Matrice pleine ++++++++
Dimensions de Adense : (10000, 10000) ; taille mémoire : 800000000 octets
++++++++ Matrice creuse ++++++++
Une matrice creuse est stockée sous forme de 3 vecteurs
	Acreuse.indices de dimension (29998,)
	Acreuse.indptr de dimension (10001,)
	Acreuse.data de dimension (29998,)
Dimensions de Acreuse : (10000, 10000) ; taille mémoire : 399980 octets
Ratio memoire: 2000.1000050002501
--- 2.184828996658325 seconds ---
--- 0.014322757720947266 seconds ---
Ratio temps  152.5424809401738


# Inversion matrice creuse avec Nb = 10^7

In [10]:
Nb = 10**7
Acreuse = sparse.eye(Nb,k=-1)-2*sparse.eye(Nb)+sparse.eye(Nb,k=1)
bdense = np.ones(Nb)
start_time = time.time()
x2 = spsolve(Acreuse,bdense)
time_creux = time.time() - start_time
print("--- %s seconds ---" % (time_creux))

--- 5.038474082946777 seconds ---
